version: '3.8'

networks:
  store_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.29.0.0/16"

services:
  mysql:
    image: mysql:8.4.0
    container_name: store-mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    networks:
      store_network:
        ipv4_address: "172.29.0.2"

  mongo:
    image: mongo:latest
    container_name: store-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      store_network:
        ipv4_address: "172.29.0.3"

  redis:
    image: redis:alpine
    container_name: store-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      store_network:
        ipv4_address: "172.29.0.4"

  nats:
    image: nats:alpine
    container_name: store-nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      store_network:
        ipv4_address: "172.29.0.5"

volumes:
  mysql_data:
  mongo_data:
